config/routes.rb
Rails.application.routes.draw do
  
  namespace :admin do
    resources :posts do
      member do
        patch 'review'
      end
    end 
    resources :users, :comments
  end
  
  resources :posts, except: [:update, :edit, :destroy]
  resources :subscriptions, only: [:create]
  
  get '/modal_show/:id', to: 'posts#modal_show'
  get '/update_post_by_date', to: 'posts#update_post_by_date'

  resources :comments, only: [:create]

  resources :replies, only: [:create]

  resources :sessions, only: [:create, :destroy]
  
  resources :votes, only: [:create]
  
  
  get '/auth/:provider/callback', to: 'sessions#create'
  
  root "posts#index"

  get '/about' => "home#index"
  
  
  

end

app/models/post.rb
class Post < ActiveRecord::Base
  has_attached_file :icon, presence: true,:styles => { :medium => "300x300>"}
  validates_attachment_content_type :icon, :content_type => /\Aimage\/.*\Z/
  validates_presence_of :icon, :title, :description, :category
  validates_format_of :ios, :android, :windows, :web, with: /https?:\/\/[\S]+/, allow_nil: true, allow_blank: true, message: "请输入正确的url格式"
  validates_length_of :description, maximum: 200, message: "请输入小于100个汉字的描述"
  validates_uniqueness_of :title, :android, :ios, :windows, :web, allow_nil: true, allow_blank: true,
  message: "该游戏已经存在"
  scope :find_by_day, -> (date) {where('created_at >= ? and created_at <= ?', date.at_beginning_of_day, date.at_end_of_day)}

  has_many :comments
  has_many :votes
  belongs_to :user
  belongs_to :category
  
  def self.recent_post(date)
    if where('created_at <= ?', date.at_end_of_day).present?
      recent_posts = find_by_day(date)
      until recent_posts.present? do
        date = date - 1.day
        recent_posts = find_by_day(date)
      end
    end
    return recent_posts.nil? ? [] : recent_posts.where(status: 1)
  end

  def as_json(options = {})
    super(only: [:id, :title ,:description]).merge({
      created_at: self.created_at.strftime("%Y-%m-%d"), 
      icon: icon_url,
      category: category_name,
      votes_count: votes_count,
      comments_count: comments_count,
      })
    end
  
    def add_visit
      update_attributes!(visit: visit + 1)
    end

    def icon_url
      icon.url(:medium)
    end

    def category_name
      self.category.name
    end
  end

app/controllers/admin/posts_controller.rb
class Admin::PostsController < ApplicationController
  http_basic_authenticate_with name: 'admin321', password: 'admin!@#$1234adminqwert'
  before_action :set_admin_post, only: [:show, :edit, :update, :destroy, :review]

  layout 'admin'
  # GET /admin/posts
  # GET /admin/posts.json
  def index
    @admin_posts = Post.all.order(created_at: :desc)
  end

  # GET /admin/posts/1
  # GET /admin/posts/1.json
  def show
    
  end

  # GET /admin/posts/new
  def new
    @admin_post = Post.new
  end

  # GET /admin/posts/1/edit
  def edit

  end

  # POST /admin/posts
  # POST /admin/posts.json
  def create
    @admin_post = Post.new(admin_post_params)

    respond_to do |format|
      if @admin_post.save
        format.html { redirect_to @admin_post, notice: 'Post was successfully created.' }
        format.json { render :show, status: :created, location: @admin_post }
      else
        format.html { render :new }
        format.json { render json: @admin_post.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /admin/posts/1
  # PATCH/PUT /admin/posts/1.json
  def update
    if @admin_post.update(admin_post_params)
      redirect_to admin_posts_path
    else
      redirect_to edit_admin_post_path(@admin_post)
    end
  end
  
  def review
    @admin_post.update_attributes(status: 1)
    redirect_to admin_posts_path
  end

  # DELETE /admin/posts/1
  # DELETE /admin/posts/1.json
  def destroy
    @admin_post.destroy
    respond_to do |format|
      format.html { redirect_to admin_posts_url, notice: 'Post was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
  # Use callbacks to share common setup or constraints between actions.
  def set_admin_post
    @admin_post = Post.find(params[:id])
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def admin_post_params
    params.require(:post).permit(:title, :description, :icon, :user_id, :ios, :android, :windows, :web, :visit, :category_id, :comments_count, :votes_count)
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :set_post, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!, only: [:new, :create]
  
  layout 'modal', only: [:modal_show]

  # GET /posts
  # GET /posts.json
  def index
    @posts = Post.recent_post(Time.now).where(status: 1)
  end

  def update_post_by_date
    date = params[:date]
    @posts = Post.order("created_at desc").recent_post(date.to_datetime - 1.day)
    render json: @posts
  end
  
  def modal_show
    @post = Post.find(params[:id])
    @post.add_visit
  end

  # GET /posts/new
  def new
    @categories = Category.all.map {|c| [c.name, c.id]}
    @post = Post.new
  end

  # GET /posts/1/edit
  def edit
  end

  # POST /posts
  # POST /posts.json
  def create
    @post = Post.new(post_params)
    @post.user = current_user
      if @post.save
        redirect_to posts_path, notice: '你的推荐的游戏提交成功，管理员审核通过后将会发布产品!感谢您的分享'
      else
        render :new
      end
  end

  # PATCH/PUT /posts/1
  # PATCH/PUT /posts/1.json
  def update
    respond_to do |format|
      if @post.update(post_params)
        format.html { redirect_to @post, notice: 'Post was successfully updated.' }
        format.json { render :show, status: :ok, location: @post }
      else
        format.html { render :edit }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /posts/1
  # DELETE /posts/1.json
  def destroy
    @post.destroy
    respond_to do |format|
      format.html { redirect_to posts_url, notice: 'Post was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_post
      @post = Post.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def post_params
      params.require(:post).permit(:title, :description, :icon, :category_id, :ios, :android, :windows, :web )
    end
end

app/helpers/admin/posts_helper.rb
module Admin::PostsHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/admin/posts/_form.html.erb
<%= simple_form_for(@admin_post) do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">
    <%= f.input :title %>
    <%= f.input :description %>
    <%= f.input :icon %>
    <%= f.input :user_id %>
    <%= f.input :ios %>
    <%= f.input :android %>
    <%= f.input :windows %>
    <%= f.input :web %>
    <%= f.input :visit %>
    <%= f.input :category_id %>
    <%= f.input :comments_count %>
    <%= f.input :votes_count %>
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/admin/posts/edit.slim
= simple_form_for([:admin, @admin_post] ,:html=> { multipart: true, class: "form-horizontal", role: "form" }) do |f|
  .form-group
    .col-lg-2
    .col-lg-10
      h6 编辑游戏信息
      p = f.error_notification
  .form-group
    label.col-lg-2.control-label  
    .col-lg-9 基本信息
  .form-group
    label.col-lg-2.control-label  原图标
    .col-lg-9
      img src=@admin_post.icon height="40" width="40"
  .form-group
    label.col-lg-2.control-label  新图标
    .col-lg-9
      = f.input :icon, as: :file, label: false
  .form-group
    label.col-lg-2.control-label  游戏类别
    .col-lg-3
      = f.input :category_id, as: :select, label: false, collection: Category.all, input_html: {class: 'input-select'}
  .form-group
    label.col-lg-2.control-label  游戏名称
    .col-lg-9
      = f.input :title, label: false,style: "max-width:40px;", type: "text", input_html: {class: 'form-control'}  
  .form-group
    label.col-lg-2.control-label  游戏简介
    .col-lg-9
      = f.input :description, label: false, style: "max-width:40px;", type: "text", input_html: {class: 'form-control'}
  .form-group
    label.col-lg-2.control-label  
    .col-lg-9 游戏平台及链接
  .form-group
    label.col-lg-2.control-label  iOS(可选)
    .col-lg-9
      = f.input :ios, label: false, style: "max-width:40px;", type: "text", input_html: {class: 'form-control'}
  .form-group
    label.col-lg-2.control-label  Android(可选)
    .col-lg-9
      = f.input :android, label: false, style: "max-width:40px;", type: "text", input_html: {class: 'form-control'}
  .form-group
    label.col-lg-2.control-label  Windows(可选)
    .col-lg-9
      = f.input :windows, label: false, style: "max-width:40px;", type: "text", input_html: {class: 'form-control'}
  .form-group
    label.col-lg-2.control-label  Web(可选)
    .col-lg-9
      = f.input :web, label: false, style: "max-width:40px;", type: "text", input_html: {class: 'form-control'}
  .form-group
    .col-lg-offset-2.col-lg-9
      button.btn.btn-primary type="submit"  Submit
      a.btn.btn-default.pull-right href=admin_posts_path  Back

app/views/admin/posts/index.html.erb
<h6>Posts</h6>

<table class="table">
  <thead>
    <tr>
      <th>Title</th>
      <!-- <th>Description</th> -->
      <th>Icon</th>
      <th>User</th>
      <!-- <th>Ios</th>
      <th>Android</th>
      <th>Windows</th>
      <th>Web</th> -->
      <th>Visit</th>
      <th>Category</th>
      <th>Comments count</th>
      <th>Votes count</th>
      <th colspan="3">Control</th>
    </tr>
  </thead>

  <tbody>
    <% @admin_posts.each do |admin_post| %>
      <tr>
        <td><%= admin_post.title %></td>
        <!-- <td><%= admin_post.description %></td> -->
        <td><img src="<%= admin_post.icon %>" height="30" width="30"></td>
        <td><%= admin_post.user_id %></td>
        <!-- <td><%= admin_post.ios %></td>
        <td><%= admin_post.android %></td>
        <td><%= admin_post.windows %></td>
        <td><%= admin_post.web %></td> -->
        <td><%= admin_post.visit %></td>
        <td><%= admin_post.category_id %></td>
        <td><%= admin_post.comments_count %></td>
        <td><%= admin_post.votes_count %></td>
        <td><%= link_to 'Show', admin_post %></td>
        <td><%= link_to 'Edit', edit_admin_post_path(admin_post) %></td>
        <td><%= link_to 'Destroy', admin_post, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%#= link_to 'New Post', new_admin_post_path %>

app/views/admin/posts/index.slim
h6 Posts
table.table
  thead
    tr
      th Title
      th Icon
      th User
      th Visit
      th Category
      th Comments count
      th Votes count
      th Created_at
      th Status
      th 审核
      th colspan="3"  Control
  tbody
    - @admin_posts.each do |admin_post|
      tr
        td= admin_post.title
        td
          img height="30" src=admin_post.icon width="30" 
        td= admin_post.user_id
        td= admin_post.visit
        td= admin_post.category_id
        td= admin_post.comments_count
        td= admin_post.votes_count
        td= admin_post.created_at
        td= admin_post.status
        td
           a href=review_admin_post_path(admin_post) data-method="patch" 
             span 通过审核
        td
           a href=post_path(admin_post) target="_blank"
            span.fui-window
        td
          a href=edit_admin_post_path(admin_post) 
            span.fui-new
        td
          a href=admin_post_path(admin_post) data-method="delete"  onclick="javascript:confirm('确定要删除吗?')"
            span.fui-cross

app/views/admin/posts/new.html.erb
<h1>New admin_post</h1>

<%= render 'form' %>

<%= link_to 'Back', admin_posts_path %>

app/views/admin/posts/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @admin_post.title %>
</p>

<p>
  <strong>Description:</strong>
  <%= @admin_post.description %>
</p>

<p>
  <strong>Icon:</strong>
  <%= @admin_post.icon %>
</p>

<p>
  <strong>User:</strong>
  <%= @admin_post.user_id %>
</p>

<p>
  <strong>Ios:</strong>
  <%= @admin_post.ios %>
</p>

<p>
  <strong>Android:</strong>
  <%= @admin_post.android %>
</p>

<p>
  <strong>Windows:</strong>
  <%= @admin_post.windows %>
</p>

<p>
  <strong>Web:</strong>
  <%= @admin_post.web %>
</p>

<p>
  <strong>Visit:</strong>
  <%= @admin_post.visit %>
</p>

<p>
  <strong>Category:</strong>
  <%= @admin_post.category_id %>
</p>

<p>
  <strong>Comments count:</strong>
  <%= @admin_post.comments_count %>
</p>

<p>
  <strong>Votes count:</strong>
  <%= @admin_post.votes_count %>
</p>

<%= link_to 'Edit', edit_admin_post_path(@admin_post) %> |
<%= link_to 'Back', admin_posts_path %>