config/routes.rb
Rails.application.routes.draw do
  
  namespace :admin do
    resources :posts do
      member do
        patch 'review'
      end
    end 
    resources :users, :comments
  end
  
  resources :posts, except: [:update, :edit, :destroy]
  resources :subscriptions, only: [:create]
  
  get '/modal_show/:id', to: 'posts#modal_show'
  get '/update_post_by_date', to: 'posts#update_post_by_date'

  resources :comments, only: [:create]

  resources :replies, only: [:create]

  resources :sessions, only: [:create, :destroy]
  
  resources :votes, only: [:create]
  
  
  get '/auth/:provider/callback', to: 'sessions#create'
  
  root "posts#index"

  get '/about' => "home#index"
  
  
  

end

app/models/user.rb
class User < ActiveRecord::Base
  validates_presence_of :provider, :uid, :name, :oauth_token, :oauth_expires_at
  
  has_many :posts
  has_many :replies
  has_many :comments
  has_many :votes

  def self.from_omniauth(auth)
    where(provider: auth.provider, uid: auth.uid.to_s).first_or_create do |user|
      user.provider = auth.provider
      user.uid = auth.uid
      user.name = auth.info.name
      user.oauth_token = auth.credentials.token
      user.oauth_expires_at = Time.at(auth.credentials.expires_at)
      user.avatar = auth.info.image
      user.save!
    end
  end
end

app/controllers/admin/users_controller.rb
class Admin::UsersController < ApplicationController
  http_basic_authenticate_with name: 'admin321', password: 'admin!@#$1234adminqwert'
  before_action :set_admin_user, only: [:show, :edit, :update, :destroy]
  layout 'admin'
  # GET /admin/users
  # GET /admin/users.json
  def index
    @admin_users = User.all
  end

  # GET /admin/users/1
  # GET /admin/users/1.json
  def show
  end

  # GET /admin/users/new
  def new
    @admin_user = User.new
  end

  # GET /admin/users/1/edit
  def edit
  end

  # POST /admin/users
  # POST /admin/users.json
  def create
    @admin_user = User.new(admin_user_params)

    respond_to do |format|
      if @admin_user.save
        format.html { redirect_to @admin_user, notice: 'User was successfully created.' }
        format.json { render :show, status: :created, location: @admin_user }
      else
        format.html { render :new }
        format.json { render json: @admin_user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /admin/users/1
  # PATCH/PUT /admin/users/1.json
  def update
    respond_to do |format|
      if @admin_user.update(admin_user_params)
        format.html { redirect_to @admin_user, notice: 'User was successfully updated.' }
        format.json { render :show, status: :ok, location: @admin_user }
      else
        format.html { render :edit }
        format.json { render json: @admin_user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /admin/users/1
  # DELETE /admin/users/1.json
  def destroy
    @admin_user.destroy
    respond_to do |format|
      format.html { redirect_to admin_users_url, notice: 'User was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_admin_user
      @admin_user = User.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def admin_user_params
      params.require(:admin_user).permit(:provider, :uid, :created_at)
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
 layout 'before_app'
 
  def  new
  end

  def edit
    
  end
  
  def show
    
  end
end

app/helpers/admin/users_helper.rb
module Admin::UsersHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/admin/users/_form.html.erb
<%= simple_form_for([:admin, @admin_user]) do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">
    <%= f.input :provider %>
    <%= f.input :uid %>
    <%= f.input :created_at %>
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/admin/users/edit.html.erb
<h1>Editing admin_user</h1>

<%= render 'form' %>

<%= link_to 'Show', @admin_user %> |
<%= link_to 'Back', admin_users_path %>

app/views/admin/users/index.html.erb
<h6>Users</h6>

<table class="table">
  <thead>
    <tr>
      <th>Provider</th>
      <th>Uid</th>
      <th>Name</th>
      <th>Created at</th>
      <th colspan="3">Control</th>
    </tr>
  </thead>

  <tbody>
    <% @admin_users.each do |admin_user| %>
      <tr>
        <td><%= admin_user.provider %></td>
        <td><%= admin_user.uid %></td>
        <td><%= admin_user.name %></td>
        <td><%= admin_user.created_at %></td>
        <td><%= link_to 'Show', admin_user %></td>
        <td><%= link_to 'Edit', edit_admin_user_path(admin_user) %></td>
        <td><%= link_to 'Destroy', admin_user, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%#= link_to 'New User', new_admin_user_path %>

app/views/admin/users/index.slim
h6 Users
table.table
  thead
    tr
      th Provider
      th Uid
      th Name
      th Created at
      / th colspan="1"  Control
  tbody
    - @admin_users.each do |admin_user|
      tr
        td= admin_user.provider
        td= admin_user.uid
        td= admin_user.name
        td= admin_user.created_at
        /td= link_to 'Show', admin_user
        /td= link_to 'Edit', edit_admin_user_path(admin_user)
        / td
        /   a href=admin_user_path(admin_user) data-method="delete"  onclick="javascript:confirm('确定要删除吗?')"
        /     span.fui-cross

app/views/admin/users/new.html.erb
<h1>New admin_user</h1>

<%= render 'form' %>

<%= link_to 'Back', admin_users_path %>

app/views/admin/users/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Provider:</strong>
  <%= @admin_user.provider %>
</p>

<p>
  <strong>Uid:</strong>
  <%= @admin_user.uid %>
</p>

<p>
  <strong>Created at:</strong>
  <%= @admin_user.created_at %>
</p>

<%= link_to 'Edit', edit_admin_user_path(@admin_user) %> |
<%= link_to 'Back', admin_users_path %>